### ISSUE TITLE
Meerlanden changed calender. 

### ISSUE THREAD

**Issue by TheLion** [jvanderzande/GarbageCalendar#1]
Unfortunately Meerlanden garbage-disposal removed it's online calender and put it all in an app and web-app, so the script doesn't retrieve anything anymore. :-(

Is there anything you can do?

**Comment by jvanderzande** [comment]
Think they work now with the XIMMIO module.
Email me your zipcode & housnr and I will test to see all works and Email you the required info.

**Comment by TheLion** [comment]
Mail sent. 

Thanks!

**Comment by jvanderzande** [comment]
.. not received anything yet in email other then your above post by github. :)

**Comment by TheLion** [comment]
> .. not received anything yet in email other then your above post by github. :)

Sent it to the Yahoo address listed on your Github profile.

**Comment by jvanderzande** [comment]
Got it ....  somehow ended up in the spambox... will email you back when tested.

**Comment by jvanderzande** [comment]
Working with XIMMIO.
