### ISSUE TITLE
Error while using Ximmio

### ISSUE THREAD

**Issue by DarkVillager** [jvanderzande/GarbageCalendar#21]
These are the log files. I'm using ximmio and it randomly jusst stopped working.
[garbagecalendar_run_m_ximmio.log](https://github.com/jvanderzande/GarbageCalendar/files/6337350/garbagecalendar_run_m_ximmio.log)
[garbagecalendar_run_update_m_ximmio.log](https://github.com/jvanderzande/GarbageCalendar/files/6337351/garbagecalendar_run_update_m_ximmio.log)
[garbagecalendar_web_m_ximmio.log](https://github.com/jvanderzande/GarbageCalendar/files/6337353/garbagecalendar_web_m_ximmio.log)

**Comment by jvanderzande** [comment]
Lets work on this with direct Email to avoid posting to much info in public forum.
Could you send me an Email to my github email address, which you can find in my profile info?
You are the second person having this and I haven't been able to get enough information to determine why it goes wrong in your setup, while all works fine for me, so would be happy to work with you to figure out why this is happening.
I have a test version locally available which does some extra logging which I will send to you, when I have received your direct email. (Language can be both Dutch or English :) )
Jos
