### ISSUE TITLE
2 containers in one day

### ISSUE THREAD

**Issue by gertvanwij** [jvanderzande/GarbageCalendar#27]
Hy Jos,

they come to us to pick up two containers a day.
we only get one e-mail, is it possible to get two e-mails?
how can we possibly solve this?

**Comment by jvanderzande** [comment]
Thought it would do that already assuming you have configured all garbage types. Could you email me (to my github email address) your logfiles when this happens, or ... send me your configfile so I can do a quick test myself?

**Comment by jvanderzande** [comment]
Fixed with commit: https://github.com/jvanderzande/GarbageCalendar/commit/8b2ba723c418fe097176d93afa976ba2db717fc8
