### ISSUE TITLE
Crash reports

### ISSUE THREAD

**Issue by FilipDem** [jvanderzande/GarbageCalendar#28]
Dear, 
Since some days, I got a systematic error and there are no "updates" of the device anymore (and all information is empty). Nothing changed on my side, so I am wondering whether it is not the site where the information is coming from.

I am have configured "m_recycleapp-be.lua".
All starts with an error in the domoticz logging: 2021-11-02 19:02:10.165 Error: EventSystem: Warning!, lua script /home/pi/domoticz/scripts/lua/script_time_garbagecalendar.lua has been running for more than 10 seconds

I checked then the logging of the script in detail and even saw "LUA Hardcrash log".

You can find here the complete error log I could capture: [Error GarbageCollector.txt](https://github.com/jvanderzande/GarbageCalendar/files/7475582/Error.GarbageCollector.txt)

Any idea what could be the reason?

Thanks for your help!

Filip

**Comment by jvanderzande** [comment]
I need all logfiles to be in a better position to understand the issue as this just tells me there is a problem getting the Data from the Website, but not what the issue could be as that log is a different one. You can also Email it in case you don't want to publicly share that data.

**Comment by FilipDem** [comment]
Hey, I included the log files before having activated the "debug" (ie ..._init.zip) and after having activated the "debug" (ie ..._with_debug.zip).
I took already a quick look, however I am not sure you will find more information.
I didn't change any script since the first use (and it was always working well). Could it be caused by an update of by linux system? It updates regularly... I am using Buster on Raspberry Pi...

[garbagecalendar_init.zip](https://github.com/jvanderzande/GarbageCalendar/files/7489116/garbagecalendar_init.zip)
[garbagecalendar_with_debug.zip](https://github.com/jvanderzande/GarbageCalendar/files/7489118/garbagecalendar_with_debug.zip)

F

**Comment by jvanderzande** [comment]
Hi Filip,

Sure it helps. :)
You are not running the latest version of the module m_recycleapp-be 
(v20211022-1800)!
For me it works fine: 3:54:07 MainScript: ==> found schedule:don 11 nov: 
gft ; vri 12 nov: pmd ; maa 15 nov: papier-karton ;

So please update to the latest github version en try again.

Cheers,
Jos

**Comment by FilipDem** [comment]
Indeed. I haven't seen there was an update done in the meantime.
Updated and works again! Thanks & sorry not having seen it myself.
