### ISSUE TITLE
rmn updated app

### ISSUE THREAD

**Issue by imdos** [jvanderzande/GarbageCalendar#36]
I've found the new RMN app and did some certificate unpinning with frida and http toolkit. The new URL is for and adress in IJsselstein for example:
3402ta 17

https://europe-west3-burgerportaal-production.cloudfunctions.net/exposed/organisations/138204213564933597/address/206321157929710806/calendar

Please let me know if you require some others which reside within the same region to check if the scripts can be rewritten.

P.S. I'm fluent in Dutch; but don't know which language is preferred.

**Comment by jvanderzande** [comment]
Hi,
I am willing to assist/make a new module for RMN, but this is a new development as I currently don't have a module for RMN. (https://www.domoticz.com/forum/viewtopic.php?p=300256#p300256)
The link you provided doesn't work for me (Unauthorized)  as I probably are missing the cookies containing the required certificates?

PS: English/Dutch are both fine for me. :)

**Comment by imdos** [comment]
Sorry; heeft nog iets werk nodig. Er is een authenticatie token benodigd. Ik heb hier al iets van informatie gepost. 
https://github.com/xirixiz/homeassistant-afvalwijzer/issues/232

**Comment by jvanderzande** [comment]
Module RMN is now supported with commit 2504b50 .
