### ISSUE TITLE
www.mijnafvalwijzer.nl has new layout?

### ISSUE THREAD

**Issue by MikeyPgit** [jvanderzande/GarbageCalendar#39]
Since about Dec 9, no data is refreshed for the garbage calendar.

garbagecalendar_m_mijnafvalwijzer_run_webupdate.log shows:
gc_main: 378: -< ========== End module m_mijnafvalwijzer.lua (v20240101-1910)
gc_main: 608:    #### Error: There are 0 data records in Datafile:/var/log/garbagecalendar_m_mijnafvalwijzer.data

I have made no modifications over the last 3 months in the parameters or source code.

The relevant site used by garbage party Saver, https://www.mijnafvalwijzer.nl/nl/4701/AB, contains in the underlying html page source all occasions for 2024 (but 2025 not shown). I assume (since also the Saver app has been updated) that the page has received a new layout, breaking the data processing. 

Your investigation is highly appreciated!

**Comment by jvanderzande** [comment]
Please provide me with the required details as [described in the Wiki](https://github.com/jvanderzande/GarbageCalendar/wiki/Testing), and I will be happy to take a look. :)

**Comment by jvanderzande** [comment]
ps: I assume the afvalkalender is moved to OPZET so you could try:

```
wmodule=m_opzet
Hostname=saver.nl
```

**Comment by MikeyPgit** [comment]
That was an excellent suggestion - this works:

websitemodule = "m_opzet"
Hostname = 'saver.nl'

Ticket closed & thanks for the rapid response!
