### ISSUE TITLE
Added Rova modules

### ISSUE THREAD

**Issue by JeroenEeuwes** [jvanderzande/GarbageCalendar#7]
I tried to add Rova modules with git from my PC, but that didn't work. It says access denied when I tried to do a git push. Could very well be my own fault, I didn't use git before. 

Anyway, I could add two files via the browser and changes in a third. I tried to get these in 1 request, but obviously I did that wrong too as there are now requests for each file separately.

Hope this helps.

**Comment by jvanderzande** [comment]
Hi Jeroen, 
GIT PUSH is only allowed for the Owner of the repository and developers I add.
I do see 3(?) pull-requests from you for adding Rova.  Normally you do the local development in a separate (new) Branch of the source, and you use this Branch to make the changes and create the Pull-Request.
Will have a look at those to see what you have done and merge when all is ok..  
I am closing this "issue" and just Emil me in case you want to further discuss this. :)   
Thanks,
Jos
