### ISSUE TITLE
garbagecalendar_run_m_mijnafvalwijzer.log shows funny NotificationTime

### ISSUE THREAD

**Issue by Muller59** [jvanderzande/GarbageCalendar#8]
when looking at the log for m_mijnafvalwijzer i see
NotificationTime:16:0 
NotificationTime:2:30

i would like to see (bold for emphasis)
NotificationTime:16:0**0** 
NotificationTime:**0**2:30

rob@VM-Dom:~$ sudo cat /var/tmp/garbagecalendar_run_m_mijnafvalwijzer.log 
@GarbageCal(m_mijnafvalwijzer): #### Sun Sep  6 13:36:00 2020 ### Start garbagecalendar script v20200613-1800
@GarbageCal(m_mijnafvalwijzer): domoticzjsonpath: /home/rob/domoticz/scripts/lua/
@GarbageCal(m_mijnafvalwijzer): datafilepath: /var/tmp/
@GarbageCal(m_mijnafvalwijzer): scriptpath: /home/rob/domoticz/scripts/lua/
@GarbageCal(m_mijnafvalwijzer): Loaded /home/rob/domoticz/scripts/lua/garbagecalendar/garbagecalendarconfig.lua.
@GarbageCal(m_mijnafvalwijzer): Loaded /home/rob/domoticz/scripts/lua/garbagecalendar/generalfuncs.lua.
@GarbageCal(m_mijnafvalwijzer): Start checking garbagetype_cfg table:
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:16:0  Garbagetype:gft
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:16:0  Garbagetype:papier
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:2:30  Garbagetype:reloaddata
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:16:0  Garbagetype:pmd
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:2:31  Garbagetype:dummy1
@GarbageCal(m_mijnafvalwijzer): Scheduled time(s) not reached yet, so nothing to do!
@GarbageCal(m_mijnafvalwijzer): #### 13:36:00 End garbagecalendar script v20200613-1800

**Comment by Muller59** [comment]
found the issue

replace line 541 in script_time_garbagecalendar.lua 

original
  dprintlog("-> NotificationTime:"..tostring(gtdata.hour)..":"..tostring(gtdata.min)..'  Garbagetype:'..tostring(tbl_garbagetype))

replacement
   dprintlog("-> NotificationTime:"..string.format("%02d", tostring(gtdata.hour))..":"..string.format("%02d", tostring(gtdata.min))..'  Garbagetype:'..tostring(tbl_garbagetype))

resultrob@VM-Dom:~$ sudo cat /var/tmp/garbagecalendar_run_m_mijnafvalwijzer.log 
@GarbageCal(m_mijnafvalwijzer): #### Sun Sep  6 14:07:00 2020 ### Start garbagecalendar script v20200613-1800
@GarbageCal(m_mijnafvalwijzer): domoticzjsonpath: /home/rob/domoticz/scripts/lua/
@GarbageCal(m_mijnafvalwijzer): datafilepath: /var/tmp/
@GarbageCal(m_mijnafvalwijzer): scriptpath: /home/rob/domoticz/scripts/lua/
@GarbageCal(m_mijnafvalwijzer): Loaded /home/rob/domoticz/scripts/lua/garbagecalendar/garbagecalendarconfig.lua.
@GarbageCal(m_mijnafvalwijzer): Loaded /home/rob/domoticz/scripts/lua/garbagecalendar/generalfuncs.lua.
@GarbageCal(m_mijnafvalwijzer): Start checking garbagetype_cfg table:
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:02:30  Garbagetype:reloaddata
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:02:31  Garbagetype:dummy1
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:16:00  Garbagetype:pmd
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:16:00  Garbagetype:gft
@GarbageCal(m_mijnafvalwijzer): -> NotificationTime:16:00  Garbagetype:papier
@GarbageCal(m_mijnafvalwijzer): Scheduled time(s) not reached yet, so nothing to do!
@GarbageCal(m_mijnafvalwijzer): #### 14:07:00 End garbagecalendar script v20200613-1800

**Comment by jvanderzande** [comment]
I've just already committed a similar change to the development branch and will merge that also into the master branch. 👍 
Thanks
